#!/bin/bash

echo "POST_CHECKOUT START"

PREVIUS_BRANCH=$(git name-rev $(git rev-parse @{-1}) --name-only)
CURRENT_BRANCH=$(git branch --show-current)

echo "PREVIUS_BRANCH: $PREVIUS_BRANCH"
echo "CURRENT_BRANCH: $CURRENT_BRANCH"

ENV_PREV_FILE=.env.${PREVIUS_BRANCH}
ENV_NEXT_FILE=.env.${CURRENT_BRANCH}


if test -f ".env"; then
    echo ".env exits."
    echo "START renaming .env to .env.$PREVIUS_BRANCH"
    mv ./.env ./${ENV_PREV_FILE}
    echo "END renaming .env to .env.$PREVIUS_BRANCH"
fi

if test -f "$ENV_NEXT_FILE"; then
    echo "$ENV_NEXT_FILE exits."
    echo "START renaming .env.$CURRENT_BRANCH to .env"
    mv ./${ENV_NEXT_FILE} ./.env
    echo "END renaming .env.$CURRENT_BRANCH to .env"
fi