#!/bin/bash

echo "POST_CHECKOUT START"

CURRENT_BRANCH=$(git branch --show-current)

echo "CURRENT_BRANCH: $CURRENT_BRANCH"

FILE=.env.${CURRENT_BRANCH}
if test -f "$FILE"; then
    echo "$FILE exits."
fi