#!/bin/bash

echo "post-checkout hook"

PREV_COMMIT=$1
POST_COMMIT=$2
BRANCH_CHECKOUT=$6

echo "PREV_COMMIT: $PREV_COMMIT"
echo "POST_COMMIT: $POST_COMMIT"
echo "BRANCH_CHECKOUT: $BRANCH_CHECKOUT"

NOCOLOR='\e[0m'
REDCOLOR='\e[37;41m'

if [[ -f composer.lock ]]; then
    DIFF=`git diff --shortstat $PREV_COMMIT..$POST_COMMIT composer.lock`
    if [[ $DIFF != "" ]]; then
        echo -e "$REDCOLOR composer.lock has changed. You must run composer install$NOCOLOR"
    fi
fi